//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Notify_Example {
	
	
	public partial class _default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl txb_token;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl txb_msg;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl msg;
		
		protected System.Web.UI.WebControls.Button ButtonSend;
	}
}
